//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My3Business.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWeatherWebService")]
    public interface IWeatherWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherWebService/Weather", ReplyAction="http://tempuri.org/IWeatherWebService/WeatherResponse")]
        string Weather();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherWebService/Weather", ReplyAction="http://tempuri.org/IWeatherWebService/WeatherResponse")]
        System.Threading.Tasks.Task<string> WeatherAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherWebServiceChannel : My3Business.ServiceReference1.IWeatherWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherWebServiceClient : System.ServiceModel.ClientBase<My3Business.ServiceReference1.IWeatherWebService>, My3Business.ServiceReference1.IWeatherWebService {
        
        public WeatherWebServiceClient() {
        }
        
        public WeatherWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Weather() {
            return base.Channel.Weather();
        }
        
        public System.Threading.Tasks.Task<string> WeatherAsync() {
            return base.Channel.WeatherAsync();
        }
    }
}
